export const StatusColor = {
    "POR-VALIDAR" : "#FFFFFF",
    "ENVIADO" : "#02A4EF",
    "RE-ENVIADO" : "#02A4EF",
    "RE-ENVIADO A L. TECNICO" : "#FEB800",
    "RE-ENVIADO A L. FUNCIONAL" : "#FEB800",
    "APROBADO POR L. TECNICO" : "#FEB800",
    "APROBADO POR L. FUNCIONAL" : "#FEB800",
    "APROBADO LIDERES" : "#7FBA00",
    "RECHAZADO POR L. TECNICO" : "#FEB800",
    "RECHAZADO POR L. FUNCIONAL" : "#FEB800",
    "RECHAZADO LIDERES" : "#F15022",
    "SIN RESPUESTA POR. L. TECNICO" : "#FEB800",
    "SIN RESPUESTA POR. L. FUNCIONAL" : "#FEB800",
    "SIN RESPUESTA LIDERES" : "#AFAFAF",
}

